### ISSUE TITLE
Shallow water solver is broken in 3D

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#167]
With recent firedrake updates, the 3D test cases fail if there's 2D-3D coupling with non-zero coupling term.

For example, the `lockExchange` example manifests this error:
```
$ python lockExchange.py -r coarse
UFL:WARNING Discontinuous Lagrange element requested on triangle * interval, creating DQ element.
Coupled time integrator: CoupledTwoStageRK
  2D time integrator: ESDIRKTrapezoid
  3D time integrator: SSPRK22ALE
  3D implicit time integrator: DIRK22
{'ksp_type': 'gmres', 'pc_type': 'fieldsplit', 'pc_fieldsplit_type': 'multiplicative'}
2D mesh: 99 nodes, 128 triangles
3D mesh: 10 layers, 1280 prisms
Horizontal element size: 1414.21 ... 1414.21 m
Vertical element size: 2.000 ... 2.000 m
Element family: dg-dg, degree: 1
Number of tracer DOFs: 7680
Number of cores: 1
Tracer DOFs per core: ~7680.0
  - dt 2d swe: 4.711801835659298
  - dt h. advection: 70.71067639983731
  - dt v. advection: 20.83333333333321
  - dt viscosity: 19.999999027690038
  - CFL adjusted dt: 2D: inf 3D: 19.999999027690038
  - chosen dt: 2D: 19.999999027690038 3D: 19.999999027690038
  - adjusted dt: 2D: 19.565217391304348 3D: 19.565217391304348
dt = 19.565217
max h diff 851.8518104386496 - 851.8518896211225
Running lock exchange problem with options:
Resolution: coarse
Reynolds number: 1.0
Use slope limiters: True
Horizontal viscosity: 1000.0
Lax-Friedrichs factor vel: 0.0
Lax-Friedrichs factor trc: 0.0
Exporting to outputs_coarse_dg-dg_tri_p1_visc-const_Re1.0_lf-vel0.0_lf-trc0.0_lim
Elem size: 1414.2135279967463 1414.2135937246817
    0     0 T=      0.00 eta norm:     0.0000 u norm:     0.0000  0.00
temp_3d mass rel. error  0.0000e+00
temp_3d overshoot 0 0
volume2d rel. error  0.0000e+00
volume3d rel. error  0.0000e+00
Traceback (most recent call last):
  File "PETSc/petscdmshell.pxi", line 322, in petsc4py.PETSc.DMSHELL_CreateFieldDecomposition
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/dmhooks.py", line 367, in create_field_decomposition
    call_setup=True)
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/dmhooks.py", line 172, in add_hook
    raise ValueError("Expecting non-empty stack")
ValueError: Expecting non-empty stack

The above exception was the direct cause of the following exception:

SystemError: <built-in method insert of list object at 0x7fd499423c48> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7fd499423c48> returned a result with an error set
Traceback (most recent call last):
  File "lockExchange.py", line 261, in <module>
    parse_options()
  File "lockExchange.py", line 257, in parse_options
    run_lockexchange(**args_dict)
  File "lockExchange.py", line 215, in run_lockexchange
    solver_obj.iterate()
  File "/home/karna/sources/thetis/thetis/solver.py", line 1164, in iterate
    update_forcings, update_forcings3d)
  File "/home/karna/sources/thetis/thetis/coupled_timeintegrator.py", line 692, in advance
    self.timesteppers.swe2d.solve_stage(i_stage, t, update_forcings)
  File "/home/karna/sources/thetis/thetis/rungekutta.py", line 559, in solve_stage
    self.solve_tendency(i_stage, t, update_forcings)
  File "/home/karna/sources/thetis/thetis/rungekutta.py", line 551, in solve_tendency
    self.solver[i_stage].solve()
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/variational_solver.py", line 264, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 557, in petsc4py.PETSc.SNES.solve
petsc4py.PETSc.Error: error code 77
[0] SNESSolve() line 4437 in /tmp/pip-req-build-zdul6tge/src/snes/interface/snes.c
[0] SNESSolve_NEWTONLS() line 225 in /tmp/pip-req-build-zdul6tge/src/snes/impls/ls/ls.c
[0] KSPSolve() line 707 in /tmp/pip-req-build-zdul6tge/src/ksp/ksp/interface/itfunc.c
[0] KSPSetUp() line 377 in /tmp/pip-req-build-zdul6tge/src/ksp/ksp/interface/itfunc.c
[0] PCSetUp() line 894 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/interface/precon.c
[0] PCSetUp_FieldSplit() line 580 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/impls/fieldsplit/fieldsplit.c
[0] PCFieldSplitSetDefaults() line 537 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/impls/fieldsplit/fieldsplit.c
[0] Petsc has generated inconsistent data
[0] Unhandled case, must have at least two fields, not 0
```

The error occurs in `self.timesteppers.swe2d.solve_stage` on the second iteration (iteration 1, RK stage 0) because the coupling term is zero during the first iteration. The coupling term is a source term in the 2D momentum equation (function `solver.fields.split_residual_2d`).

The error only occurs if fieldsplit is used in the 2D solver. The default solver_parameters  are `{'ksp_type': 'gmres', 'pc_type': 'fieldsplit', 'pc_fieldsplit_type': 'multiplicative', 'snes_type': 'newtonls'}`.

**Comment by tkarna** [comment]
Here's an attempt for a minimal failing example, which produces a similar error:

```
from firedrake import *

mesh = UnitSquareMesh(10, 10)
V_u = VectorFunctionSpace(mesh, 'DG', 1)
V_eta = FunctionSpace(mesh, 'DG', 1)
V = MixedFunctionSpace([V_u, V_eta])

test = TestFunction(V)
test_u, test_eta = TestFunctions(V)

f = Function(V_u, name='source')
solution = Function(V, name='solution')
solution_old = Function(V, name='solution old')

u_source = f
F = - inner(solution_old, test) * dx + inner(u_source, test_u) * dx


solver_parameters = {
    'ksp_type': 'gmres',
    'pc_type': 'fieldsplit',
    'pc_fieldsplit_type': 'multiplicative',
    'snes_type': 'newtonls'
}
problem = NonlinearVariationalProblem(F, solution)
solver = NonlinearVariationalSolver(problem,
                                    solver_parameters=solver_parameters)

x, y = SpatialCoordinate(mesh)
g = Function(V_u, name='aux')
g.interpolate(as_vector((x, y)))

f.assign(Constant((1e-4, 1e-3)))

print(F)

for i in range(3):
    print(i)
    solver.solve()
    print(norm(solution))
```

If `f` is non-zero we get:
```
{ -1 * (conj(((v_0) : (w_6)))) } * dx(<Mesh #1>[everywhere], {})
  +  { conj((([v_0[0], v_0[1]]) : (w_2))) } * dx(<Mesh #1>[everywhere], {})
0
Traceback (most recent call last):
  File "PETSc/petscdmshell.pxi", line 322, in petsc4py.PETSc.DMSHELL_CreateFieldDecomposition
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/dmhooks.py", line 369, in create_field_decomposition
    ctxs = ctx.split([(i, ) for i in range(len(W))])
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/solving_utils.py", line 235, in split
    form_compiler_parameters=problem.form_compiler_parameters)
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/variational_solver.py", line 80, in __init__
    check_pde_args(self.F, self.J, self.Jp)
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/variational_solver.py", line 27, in check_pde_args
    raise ValueError("Provided Jacobian is not a bilinear form")
ValueError: Provided Jacobian is not a bilinear form

The above exception was the direct cause of the following exception:

SystemError: <built-in method insert of list object at 0x7f9ef9f63e48> returned a result with an error set
Exception ignored in: 'petsc4py.PETSc.traceback'
SystemError: <built-in method insert of list object at 0x7f9ef9f63e48> returned a result with an error set
Traceback (most recent call last):
  File "swe_example.py", line 43, in <module>
    solver.solve()
  File "/home/karna/temp/firedrake/src/firedrake/firedrake/variational_solver.py", line 264, in solve
    self.snes.solve(None, work)
  File "PETSc/SNES.pyx", line 557, in petsc4py.PETSc.SNES.solve
petsc4py.PETSc.Error: error code 77
[0] SNESSolve() line 4437 in /tmp/pip-req-build-zdul6tge/src/snes/interface/snes.c
[0] SNESSolve_NEWTONLS() line 225 in /tmp/pip-req-build-zdul6tge/src/snes/impls/ls/ls.c
[0] KSPSolve() line 707 in /tmp/pip-req-build-zdul6tge/src/ksp/ksp/interface/itfunc.c
[0] KSPSetUp() line 377 in /tmp/pip-req-build-zdul6tge/src/ksp/ksp/interface/itfunc.c
[0] PCSetUp() line 894 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/interface/precon.c
[0] PCSetUp_FieldSplit() line 580 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/impls/fieldsplit/fieldsplit.c
[0] PCFieldSplitSetDefaults() line 537 in /tmp/pip-req-build-zdul6tge/src/ksp/pc/impls/fieldsplit/fieldsplit.c
[0] Petsc has generated inconsistent data
[0] Unhandled case, must have at least two fields, not 0
```

The difference is that this example dies with the above error even with and older firedrake version where the lock exchange test (and others) used to work.

**Comment by wence-** [comment]
I think I can fix this, although I note that your minimal example is kind of weird: the residual doesn't depend on the variable you're solving for. Changing it to `F = - inner(solution_old - solution, test)*dx ...` works though.

**Comment by wence-** [comment]
Can you confirm wence/fix/dmhooks-breadcrumbs fixes things in the Thetis for you?

**Comment by tkarna** [comment]
> I think I can fix this, although I note that your minimal example is kind of weird
Aaargh, it's been too long since I have written solvers.

Yes, your fix works for the broken tests I've encountered.
